//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSessia2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentSubjects
    {
        public int Id { get; set; }
        public int IdDepartment { get; set; }
        public int IdSubject { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
