//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSessia2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user25Entities : DbContext
    {
        public user25Entities()
            : base("name=user25Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentType> AssessmentType { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DepartmentSubjects> DepartmentSubjects { get; set; }
        public virtual DbSet<EducationForm> EducationForm { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
