//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSessia2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects()
        {
            this.DepartmentSubjects = new HashSet<DepartmentSubjects>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Semester { get; set; }
        public int IdSpeciality { get; set; }
        public int LectureHours { get; set; }
        public int CourseProjectHours { get; set; }
        public int AssessmentType { get; set; }
    
        public virtual AssessmentType AssessmentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSubjects> DepartmentSubjects { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
